package_rename_config:
  android:
    app_name: WAGUS
    package_name: com.silnt.wagus
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: WAGUS
    bundle_name: WAGUS
    package_name: com.silnt.wagus