name: wagus
description: "WAGUS is a coin that is tied to the WAGUS App, and offers exclusive benefits to its holders."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  go_router: ^14.8.1
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  solana_wallet_adapter: ^0.1.5
  app_links: ^6.4.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.1.0
  privy_flutter: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_rename: ^1.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/icons/
    - lib/.env