name: wagus
description: "WAGUS is a coin that is tied to the WAGUS App, and offers exclusive benefits to its holders."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.37+38

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  go_router: ^14.8.1
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  app_links: ^6.4.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.1.0
  privy_flutter: ^0.0.8
  solana_web3:
    git:
      url: https://github.com/silnt-awaken/solana-web3.git
      ref: master
  dio: ^5.8.0+1
  cryptofont: ^1.0.2+1
  flutter_launcher_icons: ^0.14.3
  pretty_string: ^1.0.1
  date_format: ^2.0.9
  file_picker: ^9.2.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  flutter_cached_pdfview: ^0.4.3
  image_gallery_saver_plus: ^4.0.1
  printing: ^5.14.2
  share_plus: ^10.1.4
  solana: ^0.31.0+1
  pointycastle: ^3.9.1
  asn1lib: ^1.6.2
  font_awesome_flutter: ^10.8.0
  firebase_messaging: ^15.2.5
  package_info_plus: ^8.3.0
  flutter_confetti: ^0.5.1
  giphy_picker: ^3.0.2
  gif_view: ^1.0.2
  dio_cache_interceptor: ^4.0.3
  dio_smart_retry: ^7.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_rename: ^1.7.1
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icons/logo.png"
  remove_alpha_ios: true
  background_color_ios: "0xFFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icon/
    - .env