// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLUa2T5oWP6TEtkfGrzsOAD6tNKZYnkc',
    appId: '1:168597906578:web:926d54991c7c7f841bb24b',
    messagingSenderId: '168597906578',
    projectId: 'wagus-app',
    authDomain: 'wagus-app.firebaseapp.com',
    storageBucket: 'wagus-app.firebasestorage.app',
    measurementId: 'G-0BPR1DJ89P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3K28W3XcY68DVb_cW0qVAP6EkS1LK1hU',
    appId: '1:168597906578:android:551766fc9c907c5e1bb24b',
    messagingSenderId: '168597906578',
    projectId: 'wagus-app',
    storageBucket: 'wagus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmg-nF40Au18zJWAPMh0YhSp9t1RnE890',
    appId: '1:168597906578:ios:a653d43c197ed9781bb24b',
    messagingSenderId: '168597906578',
    projectId: 'wagus-app',
    storageBucket: 'wagus-app.firebasestorage.app',
    iosBundleId: 'com.silnt.wagus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmg-nF40Au18zJWAPMh0YhSp9t1RnE890',
    appId: '1:168597906578:ios:ba60c8ddc491be081bb24b',
    messagingSenderId: '168597906578',
    projectId: 'wagus-app',
    storageBucket: 'wagus-app.firebasestorage.app',
    iosBundleId: 'com.example.wagus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLUa2T5oWP6TEtkfGrzsOAD6tNKZYnkc',
    appId: '1:168597906578:web:cb3a0e633c548d0d1bb24b',
    messagingSenderId: '168597906578',
    projectId: 'wagus-app',
    authDomain: 'wagus-app.firebaseapp.com',
    storageBucket: 'wagus-app.firebasestorage.app',
    measurementId: 'G-R45FNFDXBX',
  );

}